# Generated by Django 5.0.4 on 2024-04-29 09:22

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Risk_reported',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Title', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Units',
            fields=[
                ('Units', models.CharField(choices=[('Human Resource', 'Human Resource'), ('CoICT', 'CoICT'), ('CoET', 'CoET'), ('SoED', 'SoED'), ('CoHU', 'CoHU'), ('SoAF', 'SoAF'), ('CoAF', 'CoAF'), ('CoNAS', 'CoNAS'), ('CoSS', 'CoSS'), ('IDS', 'IDS'), ('UDSoL', 'UDSoL'), ('SJMC', 'SJMC'), ('SoMG', 'SoMG'), ('UDSE', 'UDSE'), ('IKS', 'IKS')], max_length=100, primary_key=True, serialize=False)),
            ],
        ),
        migrations.CreateModel(
            name='Users',
            fields=[
                ('Fullname', models.CharField(max_length=200, primary_key=True, serialize=False)),
                ('JobTitle', models.CharField(choices=[('RiskManager', 'RiskManager'), ('RiskChampion', 'RiskChampion')], max_length=25)),
                ('Department', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='udsm_risk_register.units')),
                ('TotalRisk', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='udsm_risk_register.risk_reported')),
            ],
        ),
    ]
