# Generated by Django 5.0.4 on 2024-05-01 15:55

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('udsm_risk_register', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Risk',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=20)),
                ('job_title', models.CharField(max_length=20)),
                ('total_risks', models.IntegerField()),
                ('status', models.CharField(max_length=10)),
                ('last_updated', models.CharField(max_length=20)),
                ('department', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='udsm_risk_register.units')),
            ],
        ),
    ]
