# Generated by Django 5.0.6 on 2024-07-02 06:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('udsm_risk_register', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mitigation',
            name='effectiveness',
            field=models.CharField(choices=[('Effective', 'Effective'), ('Partial Effective', 'Partial Effective'), ('Ineffective', 'Ineffective')], max_length=400),
        ),
        migrations.AlterField(
            model_name='mitigation',
            name='mitigation',
            field=models.TextField(max_length=400),
        ),
        migrations.AlterField(
            model_name='risk',
            name='Description',
            field=models.TextField(max_length=400),
        ),
        migrations.AlterField(
            model_name='risk',
            name='status',
            field=models.CharField(choices=[('Submitted', 'Submitted'), ('Active', 'Active'), ('Pending', 'Pending'), ('Resolved', 'Resolved'), ('Closed', 'Closed')], max_length=10),
        ),
    ]
