# Generated by Django 5.0.6 on 2024-05-08 21:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('udsm_risk_register', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='risk',
            name='id',
            field=models.AutoField(choices=[('C1', 'C1'), ('C2', 'C2'), ('C3', 'C3'), ('C4', 'C4')], primary_key=True, serialize=False),
        ),
    ]
