# Generated by Django 5.0.6 on 2024-07-03 12:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("udsm_risk_register", "0001_initial"),
    ]

    operations = [
        migrations.RenameField(
            model_name="risk",
            old_name="title",
            new_name="Risk_title",
        ),
        migrations.AlterField(
            model_name="risk",
            name="status",
            field=models.CharField(
                choices=[
                    ("Submitted", "Submitted"),
                    ("Active", "Active"),
                    ("Pending", "Pending"),
                    ("Resolved", "Resolved"),
                    ("Closed", "Closed"),
                ],
                max_length=10,
            ),
        ),
    ]
