# Generated by Django 5.0.6 on 2024-06-16 18:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('udsm_risk_register', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('RiskManager', 'RiskManager'), ('RiskChampion', 'RiskChampion')], max_length=25, null=True),
        ),
    ]
