# Generated by Django 5.0.6 on 2024-06-16 18:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('udsm_risk_register', '0002_alter_user_role'),
    ]

    operations = [
        migrations.AlterField(
            model_name='unit',
            name='Unit_id',
            field=models.AutoField(default=1, primary_key=True, serialize=False),
        ),
    ]
