# Generated by Django 5.0.6 on 2024-06-16 18:56

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('udsm_risk_register', '0003_alter_unit_unit_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='unit',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='udsm_risk_register.unit'),
        ),
    ]
