# Generated by Django 5.0.6 on 2024-07-02 22:57

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('udsm_risk_register', '0003_alter_riskdetails_causes'),
    ]

    operations = [
        migrations.AddField(
            model_name='risk',
            name='approving_manager',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='approved_risks', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='risk',
            name='status',
            field=models.CharField(choices=[('Pending', 'Pending'), ('Proved', 'Proved')], max_length=10),
        ),
    ]
