# Generated by Django 5.0.4 on 2024-05-08 22:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('udsm_risk_register', '0003_alter_risk_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='risk',
            name='id',
            field=models.CharField(choices=[('C1', 'C1'), ('C2', 'C2'), ('C3', 'C3'), ('C4', 'C4')], max_length=10, primary_key=True, serialize=False),
        ),
    ]
