# Generated by Django 5.0.6 on 2024-07-03 20:53

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('udsm_risk_register', '0004_risk_approving_manager_alter_risk_status'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='risk',
            name='mitigation',
        ),
        migrations.AddField(
            model_name='risk',
            name='RiskCategory',
            field=models.CharField(choices=[('Governance', 'Governance'), ('Health Safety and welfare', 'Health Safety and welfare'), ('Fraud and Corruption', 'Fraud and Corruption'), ('Research and consultancy', 'Research and consultancy'), ('Academic', 'Academic'), ('Compliance', 'Compliance'), ('Human Capital', 'Human Capital'), ('ICT', 'ICT'), ('Gender', 'Gender'), ('Infrastructure Management', 'Infrastructure Management'), ('Operational', 'Operational')], max_length=100, null=True, verbose_name='Risk Category'),
        ),
        migrations.AlterField(
            model_name='risk',
            name='Description',
            field=models.CharField(max_length=400, verbose_name='Risk Description'),
        ),
        migrations.AlterField(
            model_name='risk',
            name='approving_manager',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='approved_risks', to=settings.AUTH_USER_MODEL, verbose_name='Approving manager'),
        ),
        migrations.AlterField(
            model_name='risk',
            name='status',
            field=models.CharField(choices=[('pending', 'pending'), ('approved', 'approved')], default='pending', max_length=10),
        ),
        migrations.AlterField(
            model_name='risk',
            name='title',
            field=models.CharField(max_length=200, verbose_name='Risk Title'),
        ),
        migrations.AlterField(
            model_name='riskdetails',
            name='consequences',
            field=models.TextField(max_length=500),
        ),
    ]
