# Generated by Django 5.0.6 on 2024-07-03 21:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('udsm_risk_register', '0006_risk_objective_risk_riskid'),
    ]

    operations = [
        migrations.AlterField(
            model_name='risk',
            name='RiskID',
            field=models.CharField(blank=True, max_length=20, null=True, unique=True, verbose_name='Risk ID'),
        ),
    ]
