# Generated by Django 5.0.6 on 2024-07-03 22:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('udsm_risk_register', '0007_alter_risk_riskid'),
    ]

    operations = [
        migrations.AddField(
            model_name='risk',
            name='Priority',
            field=models.CharField(blank=True, choices=[('Very high', 'Very High'), ('High', 'High'), ('Moderate', 'Moderate'), ('Low', 'Low'), ('Very Low', 'Very Low')], max_length=50, null=True),
        ),
    ]
