# Generated by Django 5.0.6 on 2024-07-03 22:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('udsm_risk_register', '0008_risk_priority'),
    ]

    operations = [
        migrations.AlterField(
            model_name='risk',
            name='Priority',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
