# Generated by Django 5.0.6 on 2024-07-03 23:04

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('udsm_risk_register', '0009_alter_risk_priority'),
    ]

    operations = [
        migrations.AlterField(
            model_name='risk',
            name='Details',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='udsm_risk_register.riskdetails', verbose_name='Risk Details'),
        ),
    ]
